# phanes-template v3.2 doc-index
# Regenerates every _index.md under the documentation tree (archive/ excluded). SOLE WRITER of
# indexes; hand-editing them is forbidden. Each entry is extracted in fallback order: DOC header
# line, then first heading, then humanized filename, so files predating the discipline are indexed
# without being edited. Rotates an index past the 500-line ceiling: newest ~100 entries stay inline,
# older entries collapse into a range line pointing to a frozen _index_archive.md. Always exits 0.
$ErrorActionPreference = 'Stop'
$INLINE = 100

function Find-PhanesRoot {
  $d = (Get-Location).Path
  while ($true) {
    if (Test-Path -LiteralPath (Join-Path $d '.phanes\config.json')) { return $d }
    $p = [System.IO.Path]::GetDirectoryName($d)
    if (-not $p -or $p -eq $d) { return $null }
    $d = $p
  }
}

$root = Find-PhanesRoot
if (-not $root) { [Console]::Error.WriteLine('doc-index: .phanes/config.json not found from this directory'); exit 0 }

$cfg = Get-Content -LiteralPath (Join-Path $root '.phanes\config.json') -Raw -Encoding utf8 | ConvertFrom-Json
$docRoot = 'documentation'
if ($cfg.docRoot) { $docRoot = $cfg.docRoot }
$docPath = Join-Path $root $docRoot
if (-not (Test-Path -LiteralPath $docPath)) { Write-Output 'doc-index: no documentation tree'; exit 0 }

function Get-DocLine([string]$file) {
  $desc = $null
  try { $head = Get-Content -LiteralPath $file -TotalCount 8 } catch { $head = @() }
  foreach ($ln in $head) {
    $m = [regex]::Match($ln, '<!--\s*DOC\s*\|\s*(.+?)\s*-->')
    if ($m.Success) { return $m.Groups[1].Value.Trim() }
  }
  foreach ($ln in $head) {
    $m = [regex]::Match($ln, '^\#{1,6}\s+(.+?)\s*$')
    if ($m.Success) { return $m.Groups[1].Value.Trim() }
  }
  $base = [System.IO.Path]::GetFileNameWithoutExtension($file)
  return ($base -replace '[-_]', ' ')
}

$written = 0

function Build-Index([string]$folder) {
  $name = Split-Path -Leaf $folder
  if ($name -eq 'archive') { return }

  $children = Get-ChildItem -LiteralPath $folder -Force -ErrorAction SilentlyContinue
  $subfolders = @($children | Where-Object { $_.PSIsContainer -and $_.Name -ne 'archive' })
  $mdFiles = @($children | Where-Object { -not $_.PSIsContainer -and $_.Extension -eq '.md' -and $_.Name -ne '_index.md' -and $_.Name -ne '_index_archive.md' })

  # Recurse first so subfolder indexes exist before we link them.
  foreach ($sf in $subfolders) { Build-Index $sf.FullName }

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("<!-- GENERATED by phanes doc-index. Do not hand-edit. -->")
  $lines.Add("# Index: $name")
  $lines.Add("")

  foreach ($sf in ($subfolders | Sort-Object Name)) {
    $lines.Add("- $($sf.Name)/ : subfolder (see $($sf.Name)/_index.md)")
  }

  $entries = @($mdFiles | Sort-Object LastWriteTime -Descending)
  if ($entries.Count -le $INLINE) {
    foreach ($f in $entries) {
      $lines.Add("- $($f.Name) : $(Get-DocLine $f.FullName)")
    }
  } else {
    $inline = $entries[0..($INLINE - 1)]
    $older = $entries[$INLINE..($entries.Count - 1)]
    foreach ($f in $inline) {
      $lines.Add("- $($f.Name) : $(Get-DocLine $f.FullName)")
    }
    $lines.Add("- ... $($older.Count) older entries collapsed into _index_archive.md")
    $arch = New-Object System.Collections.Generic.List[string]
    $arch.Add("<!-- GENERATED by phanes doc-index. Frozen overflow of _index.md. -->")
    $arch.Add("# Index archive: $name")
    $arch.Add("")
    foreach ($f in $older) {
      $arch.Add("- $($f.Name) : $(Get-DocLine $f.FullName)")
    }
    Set-Content -LiteralPath (Join-Path $folder '_index_archive.md') -Value ($arch -join "`n") -Encoding utf8
  }

  Set-Content -LiteralPath (Join-Path $folder '_index.md') -Value ($lines -join "`n") -Encoding utf8
  $script:written++
}

Build-Index $docPath
Write-Output "doc-index: regenerated $written index file(s)"
exit 0
