#!/bin/sh
# phanes-template v3.2 doc-index
# Regenerates every _index.md under the documentation tree (archive/ excluded). SOLE WRITER of
# indexes; hand-editing them is forbidden. Each entry is extracted in fallback order: DOC header
# line, then first heading, then humanized filename. Rotates an index past ~100 entries: the newest
# entries (by sorted filename) stay inline, older entries collapse into a range line pointing to a
# frozen _index_archive.md. Always exits 0.
INLINE=100

find_root() {
  d=$(pwd)
  while [ -n "$d" ] && [ "$d" != "/" ]; do
    [ -f "$d/.phanes/config.json" ] && { printf '%s' "$d"; return 0; }
    d=$(dirname "$d")
  done
  [ -f "/.phanes/config.json" ] && { printf '%s' "/"; return 0; }
  return 1
}

cfg_str() {
  grep -o "\"$1\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$2" 2>/dev/null | head -1 \
    | sed 's/.*:[[:space:]]*"\(.*\)"$/\1/'
}

root=$(find_root) || { echo "doc-index: .phanes/config.json not found from this directory" >&2; exit 0; }
docRoot=$(cfg_str docRoot "$root/.phanes/config.json"); [ -z "$docRoot" ] && docRoot=documentation
docPath="$root/$docRoot"
[ -d "$docPath" ] || { echo "doc-index: no documentation tree"; exit 0; }

doc_line() { # doc_line FILE
  f=$1
  d=$(grep -o '<!--[[:space:]]*DOC[[:space:]]*|[[:space:]]*[^>]*-->' "$f" 2>/dev/null | head -1 \
    | sed 's/<!--[[:space:]]*DOC[[:space:]]*|[[:space:]]*//; s/[[:space:]]*-->.*//')
  if [ -n "$d" ]; then printf '%s' "$d"; return; fi
  h=$(grep -m1 -E '^#{1,6}[[:space:]]' "$f" 2>/dev/null | sed -E 's/^#{1,6}[[:space:]]*//')
  if [ -n "$h" ]; then printf '%s' "$h"; return; fi
  basename "$f" .md | tr '-_' '  '
}

countfile=$(mktemp)
echo 0 > "$countfile"

find "$docPath" -type d ! -path '*/archive' ! -path '*/archive/*' | while IFS= read -r folder; do
  name=$(basename "$folder")
  idx="$folder/_index.md"
  tmp=$(mktemp)
  printf '<!-- GENERATED by phanes doc-index. Do not hand-edit. -->\n# Index: %s\n\n' "$name" > "$tmp"

  # Subfolders (excluding archive).
  for sf in "$folder"/*/; do
    [ -d "$sf" ] || continue
    sfn=$(basename "$sf")
    [ "$sfn" = "archive" ] && continue
    printf -- '- %s/ : subfolder (see %s/_index.md)\n' "$sfn" "$sfn" >> "$tmp"
  done

  # Markdown files (excluding generated indexes), sorted by name.
  files=$(ls "$folder" 2>/dev/null | grep -E '\.md$' | grep -vE '^_index\.md$|^_index_archive\.md$' | sort)
  total=$(printf '%s\n' "$files" | grep -c . )

  if [ "$total" -le "$INLINE" ]; then
    printf '%s\n' "$files" | while IFS= read -r fn; do
      [ -n "$fn" ] || continue
      printf -- '- %s : %s\n' "$fn" "$(doc_line "$folder/$fn")" >> "$tmp"
    done
  else
    # Newest ~INLINE (last by sorted name) stay inline; the rest go to the archive index.
    split=$((total - INLINE))
    older=$(printf '%s\n' "$files" | head -n "$split")
    newer=$(printf '%s\n' "$files" | tail -n "$INLINE")
    arch="$folder/_index_archive.md"
    printf '<!-- GENERATED by phanes doc-index. Frozen overflow of _index.md. -->\n# Index archive: %s\n\n' "$name" > "$arch"
    printf '%s\n' "$older" | while IFS= read -r fn; do
      [ -n "$fn" ] || continue
      printf -- '- %s : %s\n' "$fn" "$(doc_line "$folder/$fn")" >> "$arch"
    done
    printf '%s\n' "$newer" | while IFS= read -r fn; do
      [ -n "$fn" ] || continue
      printf -- '- %s : %s\n' "$fn" "$(doc_line "$folder/$fn")" >> "$tmp"
    done
    printf -- '- ... %s older entries collapsed into _index_archive.md\n' "$split" >> "$tmp"
  fi

  mv "$tmp" "$idx"
  n=$(cat "$countfile"); echo $((n + 1)) > "$countfile"
done

written=$(cat "$countfile"); rm -f "$countfile"
echo "doc-index: regenerated $written index file(s)"
exit 0
